### ISSUE TITLE
Installer with autostart

### ISSUE THREAD

**Issue by DavidM42** [PetePriority/chicony-ir-toggle#2]
I thought about maybe writing an installer or package for this to easily install it and have it autostart on boot to have the IR emitter ready on first login. Would you be interested in that?

**Comment by PetePriority** [comment]
Since this is feels like a workaround and I don't know if this is the proper way to do it, I think a package is not quite what we need yet. I'll contact the v4l2 and/or uvcvideo mailing list to see if they have any suggestions. For now, however, we could probably expand on the cmake installation instructions and requirements. 

In regards to auto-starting this on boot, the most natural way to do this should be a udev rule. I've added the udev-rule branch that installs a udev rule executing the binary on boot.

**Comment by DavidM42** [comment]
I looked into your udev branch and sadly always got this error trying to compile it with cmake
```
CMake Error at CMakeLists.txt:11 (install):
  install TARGETS given no RUNTIME DESTINATION for executable target
  "chicony-ir-toggle".
```
I don't know anything about cmake and used gcc to compile the version I currently use

**Comment by PetePriority** [comment]
Weird. On my system I didn't have to specify the RUNTIME DESTINATION. I've added it now.

I also had to add a script to `/lib/systemd/system-sleep/` to run the command after waking from suspend/hibernate.

**Comment by DavidM42** [comment]
Wow great now everything works perfect as I wanted it 👍

> Weird. On my system I didn't have to specify the RUNTIME DESTINATION. I've added it now.

Maybe I have a newer make version since I run PopOS! 19.10
```
:~$ make --version
GNU Make 4.2.1
```
One last thing would maybe be to add an easy way to remove the scripts/binaries from the system again so like an uninstall command

**Comment by PetePriority** [comment]
The installed files are listed in `build/install_manifest.txt`. You'd have to delete them manually. Alternatively, you'd have to create a package for the distribution you're using. For Debian based distros `checkinstall` does that automatically (call `checkinstall` instead of `make install`).

**Comment by DavidM42** [comment]
Ah thanks. Good to know about checkinstall. Now that I have it installed via `make install` I'll just leave it that way I think
